#!/bin/sh
set -e

VERSION_FILE='.cache/node.version'
if [ 'package.json' -nt "$VERSION_FILE" ]; then
  mkdir -p '.cache'
  echo "Resolving node version..."
  sh/resolve-node-version > $VERSION_FILE
fi

VERSION=$(cat $VERSION_FILE)
if [ -z "$VERSION" ]; then
  echo >&2 "Failed to resolve node version."
  cat "$VERSION_FILE"
  rm -f "$VERSION_FILE"
  exit 1
fi

./sh/crun "node:$VERSION" "$@"
