#!/bin/sh
set -e

VERSION_FILE='.cache/mongodb.version'
if [ 'package.json' -nt "$VERSION_FILE" ]; then
  rm -f "$VERSION_FILE"
  mkdir -p '.cache'
  echo "Resolving mongodb version..."
  sh/resolve-mongodb-version > $VERSION_FILE
fi

VERSION=$(cat $VERSION_FILE)
if [ -z "$VERSION" ]; then
  echo >&2 "Failed to resolve mongodb version."
  cat "$VERSION_FILE"
  rm -f "$VERSION_FILE"
  exit 1
fi

./sh/crun "mongo:$VERSION" "$@"
