#!/bin/sh
set -e
if [ -x './.bin/docker-compose' ]; then
  ./.bin/docker-compose $@
elif hash docker-compose 2> /dev/null; then
  docker-compose $@
else
  echo >&2 "Failed to locate docker-compose."
  exit 1
fi
