#!/bin/sh
set -e
PATH="$PATH:./.bin/"

if hash docker-compose 2> /dev/null; then
  exit 0
fi

curl -sS -L https://github.com/docker/compose/releases/download/1.4.0/docker-compose-`uname -s`-`uname -m` > docker-compose
chmod +x docker-compose
mkdir -p .bin/
mv docker-compose ./.bin/

# https://github.com/travis-ci/travis-ci/issues/4778
# https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
