#!/bin/sh
set -e
PATH="$PATH:./.bin/"
DOCKER_COMPOSE_VERSION=${DOCKER_COMPOSE_VERSION-1.4.2}

if [ -x './.bin/docker-compose' ]; then
  exit 0 #assuming locally installed version is correct
elif hash docker-compose 2> /dev/null; then
  INSTALLED_VERSION=$(docker-compose --version | grep docker-compose | awk '{print $3}' | tr -d '\n')
  if [ "$INSTALLED_VERSION" == "$DOCKER_COMPOSE_VERSION" ]; then
    exit 0
  else
    echo >&2 "Installed docker-compose version ($INSTALLED_VERSION) differs from expected ($DOCKER_COMPOSE_VERSION)"
  fi
else
  echo >&2 "docker-compose not found"
fi

DOCKER_COMPOSE_INSTALL_URL="https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m`"
echo "Installing docker-compose from $DOCKER_COMPOSE_INSTALL_URL"
curl -sS -L "$DOCKER_COMPOSE_INSTALL_URL" > docker-compose
chmod +x docker-compose
mkdir -p .bin/
mv docker-compose ./.bin/
