#!/bin/sh
set -e
PATH="$PATH:./.bin/"
DOCKER_COMPOSE_VERSION=${DOCKER_COMPOSE_VERSION-1.4.2}

BIN_TARGET='./.bin/docker-compose'
if [ -x $BIN_TARGET ]; then
  EXISTING_DC=$BIN_TARGET
elif hash docker-compose 2> /dev/null; then
  EXISTING_DC='docker-compose'
else
  echo >&2 "docker-compose not found"
  EXISTING_DC=''
fi

if [ "$EXISTING_DC" ]; then
  INSTALLED_VERSION=$($EXISTING_DC --version | grep docker-compose | awk '{print $3}' | tr -d '\n')
  if [ "$INSTALLED_VERSION" == "$DOCKER_COMPOSE_VERSION" ]; then
    exit 0
  else
    echo >&2 "Installed docker-compose version ($INSTALLED_VERSION) differs from expected ($DOCKER_COMPOSE_VERSION)"
  fi
fi

DOCKER_COMPOSE_INSTALL_URL="https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m`"
echo "Installing docker-compose from $DOCKER_COMPOSE_INSTALL_URL"
mkdir -p .bin/
curl -sS -L "$DOCKER_COMPOSE_INSTALL_URL" > $BIN_TARGET
chmod +x $BIN_TARGET
