#!/bin/bash
set -e

IMAGE="$1"
VERSION_FILE="./.cache/$IMAGE.version"

if [ ! -f "$VERSION_FILE" ] || [ "./package.json" -nt "$VERSION_FILE" ]; then
  rm -f "$VERSION_FILE"

  echo >&2 "Resolving $IMAGE version..."
  VERSION=$(sh/resolve-$IMAGE-version)

  mkdir -p './.cache'
  echo $VERSION > $VERSION_FILE
else
  VERSION=$(cat $VERSION_FILE)
fi

if [ -z "$VERSION" ]; then
  echo >&2 "Failed to resolve $IMAGE version."
  cat "$VERSION_FILE"
  rm -f "$VERSION_FILE"
  exit 1
fi

echo $VERSION
