#!/bin/bash
set -e

if hash jq 2> /dev/null; then
  VERSION=$(jq -r '.engines.node' package.json)
  curl -sS "https://semver.io/node/resolve/$VERSION"
else
  curl -sS https://semver.io/node/stable
fi
