#!/bin/sh
set -e

IMAGE="$1"
VERSION_FILE="./.cache/$IMAGE.version"

if [ ! -f "$VERSION_FILE" ] || [ "./package.json" -nt "$VERSION_FILE" ]; then
  mkdir -p './.cache'
  echo >&2 "Resolving $IMAGE version..."
  "sh/resolve-$IMAGE-version" > $VERSION_FILE
fi

VERSION=$(cat $VERSION_FILE)
if [ -z "$VERSION" ]; then
  echo >&2 "Failed to resolve $IMAGE version."
  cat "$VERSION_FILE"
  rm -f "$VERSION_FILE"
  exit 1
fi

echo $VERSION
